name: 'ERCX Classifier'
description: 'Run the ERCX classifier'
inputs:
  infura_api_key:
    description: "The infura API key to be used with forge's fork mainnet mode"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
